[package]
name = "whitesynth"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
fft-convolver = "0.2.0"
hound = "3.5.1"
log = "0.4.21"
log4rs = "1.3.0"
midir = "0.10.0"
riff = "2.0.0"
